sonar.projectKey=ffc-ahwr-event
sonar.organization=defra

sonar.links.homepage=https://github.com/DEFRA/ffc-ahwr-event
sonar.links.ci=https://github.com/DEFRA/ffc-ahwr-event/actions
sonar.links.scm=https://github.com/DEFRA/ffc-ahwr-event
sonar.links.issue=https://github.com/DEFRA/ffc-ahwr-event/issues

sonar.sources=ffc-ahwr-event/
sonar.tests=test/

sonar.javascript.lcov.reportPaths=test-output/lcov.info
